# Generated by Django 5.1.1 on 2024-11-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Masuk', 'Surat Masuk'), ('Keluar', 'Surat Keluar')], max_length=6)),
                ('nomor_surat', models.CharField(max_length=100, unique=True)),
                ('tanggal_surat', models.DateField()),
                ('pengirim', models.CharField(max_length=100)),
                ('penerima', models.CharField(max_length=100)),
                ('perihal', models.TextField()),
                ('file_surat', models.FileField(upload_to='uploads/surat/')),
            ],
        ),
    ]
